### PR TITLE
Split resolved into a separate package, it's harmful on boxes running DNS servers

### PR DESCRIPTION
**Pull request by berolinux**
systemd-resolved should be uninstallable -- on boxes that serve as DNS servers, boxes that aren't networked, etc. So it's better off being a separate package that is installed by default

### CODE REVIEW

**Comment by tpgxyz** [comment]
This new subpackage needs to be added to iso, second I'd add Recommends on it so when installing in chroot and similar you will end up in a system with working name resolution.

Why not to fix DNS servers? There must be some fix for this.

**Comment by tpgxyz** [comment]
Looks like fix is described here

https://www.freedesktop.org/software/systemd/man/resolved.conf.html
Adding to /etc/systemd/resolved.conf
`DNSStubListener=no`
will switch off binding to port 53, so any DNS server will not be affected.

I'd suggest to add some %post or stub config file to our DNS server packages, rather than splitting stuff inside systemd.

**Comment by berolinux** [comment]
I'd say both -- there are situations in which resolved is completely useless (e.g. non-networked embedded device), and there are other situations in which you may not want it (e.g. if you're running a full-fledged DNS on the same box), so there should be a way to uninstall it (other stuff still works using the traditional resolver).

Certainly can't hurt to make DNS servers add DNSStubListener=no to be able to coexist at the same time.

**Review by abucodonosor — COMMENTED** [review]
I didn't look but I think NM is using symlinks for his resolver which comes from systemd bc we removed resolvconf(openresolv) a while ago.

The PR look good but before merging that we should look what NM does.

**Comment by tpgxyz** [comment]
I stronglu recomment to fix other packages that provides DNS servers to provide configuration snippets /usr/lib/systemd/systemd-resolve.conf.d/
with
`DNSStubListener=no`


PR looks good as systemd requires %{libnss_resolve} which requires systemd-resolved

**Review by tpgxyz — APPROVED** [review]
ok

**Pull request merged**
