### PR TITLE
add initial support for systemd preset files OpenMandrivaAssociation/OpenMandrivaLx#7

### PR DESCRIPTION
**Pull request by tpgxyz**
Initial support for https://github.com/OpenMandrivaAssociation/OpenMandrivaLx/issues/7

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
At first glance, it looks good, but I'll do some further review a bit later.

**Comment by Conan-Kudo** [comment]
On further reflection, I'm not sure what we want this for? What's the use case?

**Comment by tpgxyz** [comment]
@Conan-Kudo We rely on preset files to enable services provides by rpm files. See tuned or sddm for example

**Comment by Conan-Kudo** [comment]
This won't trigger when those packages are installed, though. This will trigger only when presets are installed or removed.

**Comment by tpgxyz** [comment]
@Conan-Kudo See, tuned rpm provides 86-tuned.preset file. So when it is installed a triggers.systemd lua script should run `systemctl -q --now preset 86-tuned.preset`

**Pull request merged**
